// packages/react/src/index.tsx
import React, { useRef, useEffect } from 'react';
import { FlipCard, type FlipCardOptions } from '@flipcard/core';

export const FlipCardReact: React.FC<{
  children: React.ReactNode;
  options?: FlipCardOptions;
}> = ({ children, options }) => {
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!ref.current) return;
    const flip = new FlipCard(ref.current, options);
    return () => flip.destroy();
  }, [options?.trigger, options?.flipped]);

  return <div ref={ref} className="flipcard">{children}</div>;
};

// packages/vue/src/index.vue
<template>
  <div ref="flipcardRef" class="flipcard">
    <slot name="default"></slot>
  </div>
</template>

<script lang="ts" setup>
import { onBeforeUnmount, onMounted, ref, toRefs } from 'vue';
import { FlipCard, FlipCardOptions } from '@flipcard/core';

interface IProps {
  children: React.ReactNode;
  options?: FlipCardOptions;
}

const props = withDefaults(defineProps<IProps>(), {
  options: () => {
    return {
      trigger: 'hover',
      flipped: false
    };
  },
});

const { options } = toRefs(props);
const flipcardRef = ref<HTMLDivElement | null>(null);
const flip = ref<FlipCard | null>(null);
onMounted(() => {
  if (!flipcardRef.value) {
    return;
  }
  flip.value = new FlipCard(flipcardRef.value, options.value);
});

onBeforeUnmount(() => {
  if (flip.value) {
    flip.value.destroy();
  }
})

</script>
